#path_to_data: data/train
path_to_data: /Users/mariam/Desktop/CelebAMask-HQ/CelebA-HQ-img
path_to_mask: masks
embeddings_path: embeddings
  
path_to_checkpoint: checkpoints
checkpoint_path: checkpoints/simclr_model_train loss ssl=0.000_epoch=49.ckpt

plt_figures: plt_figures
