path_to_train_data: "data/train"
path_to_test_data: "data/test"
checkpoint_path: "lightning_logs/version_0/checkpoints/epoch=9-step=90.ckpt"

log_steps: 10
num_workers: 8
batch_size: 4
seed: 1
max_epochs: 10
resolution: 128
num_ftrs: 32